use std::collections::BTreeMap;

use litellm_model_catalog::PricingCatalog;
use litellm_traces::estimate_cost;
use rstest::rstest;
use serde::Deserialize;
use serde_json::{Map, Value};

#[derive(Deserialize)]
struct Reference {
    test: String,
    attributes: BTreeMap<String, String>,
    catalog: Map<String, Value>,
    expected: Option<f64>,
}

#[rstest]
#[case::standard_cache_usage_uses_inclusive_input_and_existing_duration_pricing_1(0)]
#[case::standard_cache_usage_uses_inclusive_input_and_existing_duration_pricing_2(1)]
#[case::standard_cache_usage_uses_inclusive_input_and_existing_duration_pricing_3(2)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_input_tokens_1(3)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_output_tokens_1_1(4)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_output_tokens_1_5_1(5)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_input_tokens_79_1(6)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_cache_read_input_tokens_bad_1(7)]
#[case::invalid_or_unsupported_usage_remains_unknown_anthropic_usage_cache_creation_ephemeral_1h_input_tokens_11_1(8)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_response_model_unknown_trace_model_1(9)]
#[case::invalid_or_unsupported_usage_remains_unknown_gen_ai_usage_input_tokens_audio_2_1(10)]
#[case::missing_usage_is_unknown_but_explicit_zero_is_priced_1(11)]
#[case::missing_usage_is_unknown_but_explicit_zero_is_priced_2(12)]
#[case::served_tier_wins_over_requested_tier_and_invalid_span_does_not_lose_batch_1(13)]
#[case::served_tier_wins_over_requested_tier_and_invalid_span_does_not_lose_batch_2(14)]
#[case::served_tier_wins_over_requested_tier_and_invalid_span_does_not_lose_batch_3(15)]
#[case::served_tier_wins_over_requested_tier_and_invalid_span_does_not_lose_batch_4(16)]
#[case::untrusted_model_names_never_fetch_metadata_false_huggingface_1(17)]
#[case::untrusted_model_names_never_fetch_metadata_false_ollama_1(18)]
#[case::untrusted_model_names_never_fetch_metadata_false_ollama_chat_1(19)]
#[case::untrusted_model_names_never_fetch_metadata_false_lemonade_1(20)]
#[case::untrusted_model_names_never_fetch_metadata_false_deepseek_1(21)]
#[case::untrusted_model_names_never_fetch_metadata_true_huggingface_1(22)]
#[case::untrusted_model_names_never_fetch_metadata_true_ollama_1(23)]
#[case::untrusted_model_names_never_fetch_metadata_true_ollama_chat_1(24)]
#[case::untrusted_model_names_never_fetch_metadata_true_lemonade_1(25)]
#[case::untrusted_model_names_never_fetch_metadata_true_deepseek_1(26)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_none_huggingface_1(27)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_none_ollama_1(28)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_none_ollama_chat_1(29)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_none_lemonade_1(30)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_none_openai_1(31)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_0_huggingface_1(32)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_0_ollama_1(33)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_0_ollama_chat_1(34)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_0_lemonade_1(35)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_0_openai_1(36)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_5_huggingface_1(37)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_5_ollama_1(38)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_5_ollama_chat_1(39)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_5_lemonade_1(40)]
#[case::static_catalog_requires_declared_rates_without_dynamic_lookup_0_5_openai_1(41)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_numeric_strings_1(42)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_tier_only_at_boundary_1(43)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_second_tier_1(44)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_above_last_tier_1(45)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_tier_uses_flat_output_1(46)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_unpriced_tier_uses_flat_1(47)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_missing_tier_output_1(48)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_no_tier_for_zero_input_1(49)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_empty_tiers_1(50)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_service_tier_only_1(51)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_service_tier_not_selected_1(
    52
)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_threshold_only_1(53)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_threshold_not_crossed_1(54)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_active_off_peak_only_1(55)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_inactive_off_peak_only_1(56)]
#[case::estimates_use_selected_rates_instead_of_requiring_flat_prices_non_token_input_1(57)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_bad_1(58)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_1_0_1(59)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_nan_1(60)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_inf_1(61)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_true_1(62)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_flat_false_1(63)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_bad_1(64)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_1_0_1(65)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_nan_1(66)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_inf_1(67)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_true_1(68)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_tier_false_1(69)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_bad_1(70)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_1_0_1(71)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_nan_1(72)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_inf_1(73)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_true_1(74)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_priority_false_1(75)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_bad_1(76)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_1_0_1(77)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_nan_1(78)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_inf_1(79)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_true_1(80)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_threshold_false_1(81)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_bad_1(82)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_1_0_1(83)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_nan_1(84)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_inf_1(85)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_true_1(86)]
#[case::invalid_selected_rates_never_become_free_or_offset_another_charge_off_peak_false_1(87)]
#[case::tier_cache_rates_preserve_defaults_explicit_zero_and_invalid_values_cache_rates0_120_1(88)]
#[case::tier_cache_rates_preserve_defaults_explicit_zero_and_invalid_values_cache_rates1_40_1(89)]
#[case::tier_cache_rates_preserve_defaults_explicit_zero_and_invalid_values_cache_rates2_none_1(90)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_0_20_140_false_1(91)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_0_20_140_true_1(92)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_20_0_140_false_1(93)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_20_0_140_true_1(94)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_none_none_140_false_1(95)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_none_none_140_true_1(96)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_20_0_none_false_1(97)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_20_0_none_true_1(98)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_0_20_none_false_1(99)]
#[case::cache_write_rate_validation_follows_used_duration_2_bad_0_20_none_true_1(100)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_none_none_none_false_1(101)]
#[case::cache_write_rate_validation_follows_used_duration_bad_2_none_none_none_true_1(102)]
#[case::unused_cache_rates_cannot_contaminate_uncached_cost_1(103)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases0_1(104)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases0_2(105)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases0_3(106)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases1_1(107)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases1_2(108)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases1_3(109)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases2_1(110)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases2_2(111)]
#[case::legacy_genai_usage_keeps_inclusive_cache_math_aliases2_3(112)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_prompt_tokens_1(113)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_completion_tokens_1(114)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_cache_creation_input_tokens_1(115)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_bad_gen_ai_usage_prompt_tokens_1(116)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_bad_gen_ai_usage_completion_tokens_1(117)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_bad_gen_ai_usage_cache_creation_input_tokens_1(118)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_prompt_tokens_2(119)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_completion_tokens_2(120)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_1_gen_ai_usage_cache_creation_input_tokens_2(121)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_18446744073709551616_gen_ai_usage_prompt_tokens_1(122)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_18446744073709551616_gen_ai_usage_completion_tokens_1(123)]
#[case::invalid_or_conflicting_numeric_alias_cannot_hide_behind_current_key_18446744073709551616_gen_ai_usage_cache_creation_input_tokens_1(124)]
#[case::legacy_cache_write_never_adds_to_an_inclusive_input_total_1(125)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers0_340_1(126)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers1_340_1(127)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers2_340_1(128)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers3_120_1(129)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers4_340_1(130)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers5_none_1(131)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers6_none_1(132)]
#[case::tier_aliases_preserve_served_precedence_and_reject_same_fact_conflicts_tiers7_none_1(133)]
#[case::actual_genai_mapper_cache_creation_is_priced_1(134)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_azure_1(135)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_azure_2(136)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_azure_ai_1(137)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_azure_ai_2(138)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_gemini_1(139)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_gemini_2(140)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_mistral_1(141)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_mistral_2(142)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_xai_1(143)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_xai_2(144)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_watsonx_1(145)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_watsonx_2(146)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_cohere_chat_1(147)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_cohere_chat_2(148)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_text_completion_openai_1(
    149
)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_text_completion_openai_2(
    150
)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_bedrock_1(151)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_bedrock_2(152)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_vertex_ai_1(153)]
#[case::canonical_provider_values_reuse_emitter_mapping_without_network_vertex_ai_2(154)]
#[case::provider_ambiguity_needs_a_unique_catalog_row_or_explicit_identifier_1(155)]
#[case::provider_ambiguity_needs_a_unique_catalog_row_or_explicit_identifier_2(156)]
#[case::provider_ambiguity_needs_a_unique_catalog_row_or_explicit_identifier_3(157)]
#[case::provider_ambiguity_needs_a_unique_catalog_row_or_explicit_identifier_4(158)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_4_5_10_132_1(159)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_4_0_10_112_1(160)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_4_none_10_120_1(161)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_none_5_10_none_1(162)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_none_2_10_120_1(163)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_none_bad_10_none_1(164)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_0_bad_10_120_1(165)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_none_bad_0_100_1(166)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_11_5_10_none_1(167)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_1_5_10_none_1(168)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_bad_5_10_none_1(169)]
#[case::reasoning_is_an_inclusive_output_subset_with_explicit_unknowns_18446744073709551616_5_10_none_1(170)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_5_1(171)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_bad_1(172)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_1_1(173)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_nan_1(174)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_inf_1(175)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_true_1(176)]
#[case::reasoning_uses_strict_selected_tier_rates_flat_false_1(177)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_5_1(178)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_bad_1(179)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_1_1(180)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_nan_1(181)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_inf_1(182)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_true_1(183)]
#[case::reasoning_uses_strict_selected_tier_rates_tier_false_1(184)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_5_1(185)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_bad_1(186)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_1_1(187)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_nan_1(188)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_inf_1(189)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_true_1(190)]
#[case::reasoning_uses_strict_selected_tier_rates_priority_false_1(191)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_5_1(192)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_bad_1(193)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_1_1(194)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_nan_1(195)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_inf_1(196)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_true_1(197)]
#[case::reasoning_uses_strict_selected_tier_rates_off_peak_false_1(198)]
#[case::selected_output_rate_can_make_a_missing_reasoning_split_irrelevant_1(199)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_1(200)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_2(201)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_3(202)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_4(203)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_5(204)]
#[case::off_peak_prices_follow_captured_time_including_nanosecond_boundaries_6(205)]
#[case::invalid_supplied_call_time_remains_unknown_bad_1(206)]
#[case::invalid_supplied_call_time_remains_unknown_9223372036854775808_1(207)]
#[case::invalid_supplied_call_time_remains_unknown_9223372036854775809_1(208)]
fn preserved_python_estimates(#[case] index: usize) {
    let line = include_str!("fixtures/pricing/python_reference.jsonl")
        .lines()
        .nth(index)
        .unwrap();
    let reference: Reference = serde_json::from_str(line).unwrap();
    let synthetic = (!reference.catalog.is_empty())
        .then(|| PricingCatalog::parse(&serde_json::to_vec(&reference.catalog).unwrap()).unwrap());
    let catalog = synthetic
        .as_ref()
        .unwrap_or_else(|| litellm_model_catalog::bundled_pricing_catalog().unwrap());
    let actual = estimate_cost(&reference.attributes, catalog);
    match (actual, reference.expected) {
        (Some(actual), Some(expected)) => assert!(
            (actual - expected).abs() <= 1e-12 * expected.abs().max(1.0),
            "{}: expected {expected}, got {actual}",
            reference.test
        ),
        _ => assert_eq!(actual, reference.expected, "{}", reference.test),
    }
}
